### ISSUE TITLE
bug: GetCheatName undefined

### ISSUE THREAD

**Issue by maximee-leroyy** [srcdslab/sm-plugin-lilac-discord#1]
Where is `GetCheatName` defined ? @Dolly132 

https://github.com/srcdslab/sm-plugin-lilac

cc @Rushaway

**Comment by Rushaway** [comment]
It's this PR. https://github.com/srcdslab/sm-plugin-lilac/pull/1

**Comment by maximee-leroyy** [comment]
@Rushaway could you take a look at my comment here so we have a working CI

- https://github.com/srcdslab/sm-plugin-lilac/pull/1#issuecomment-1475996945

**Comment by Rushaway** [comment]
It was introduced in https://github.com/srcdslab/sm-plugin-lilac/commit/dc1044c0679a3d2c99335666a2cb5f534652b099#diff-7cd23b5cc8441642e616253d1271d9995103df194d698bb0b0b733696c0e55c3R82
